title: 食物识别系统
description: 基于卷积神经网络的食物识别分类系统的设计与实现
about:

  这是一个基于卷积神经网络的食物图像分类系统.

  项目由 [贾浩](https://joker6934.github.io/) 完成



code: https://github.com/Joker6934/graduate-project/web-deep-learning-classifier

sampleImages:
  - name: 千层面
    url: https://upload.wikimedia.org/wikipedia/commons/b/ba/Lasagne_-_stonesoup.jpg
  - name: 寿司
    url: https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg
  - name: 华夫饼
    url: https://upload.wikimedia.org/wikipedia/commons/5/5b/Waffles_with_Strawberries.jpg
  - name: 茄子 (不在数据集中)
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: 桌子 (不在数据集中且不是食物)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
